name: PersonalWebsite

on:
  push:
    branches: 
      - 'master'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses : actions/checkout@v1
      
      - name: Install libraries
        run : npm install
      
      - name: Build the project
        run : npm run generate
        
      - name: Send folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: "22"
          source: "distPersonal"
          target: "/var/www/html"
    
